
UPDATE A SET    
	   PRIORITE = CASE
	  WHEN PERFIL_CLIENTE = 'CO1_CP' THEN 1 
	  WHEN PERFIL_CLIENTE = 'CO1_CE1' THEN 2 
	  WHEN PERFIL_CLIENTE = 'APTO – CANCELAR CP' THEN 3 
	  WHEN PERFIL_CLIENTE = 'COMBO_MULTI' THEN 4 
	  WHEN PERFIL_CLIENTE = 'COMBO_MULTI_CO1_CE1' THEN 5 
	  ELSE 99 END ,
	   LIB_STATUS = NULL,
       NIVABS = 0, 
       NBAPPELS = 0, 
       RAPPEL = 'Z99999999999', 
       ERRN1 = NULL,
       STATUS = NULL,
       ID_TV = NULL, 
       HEURE = NULL, 
       TV = NULL, 
       DUREE = 0, 
       VERSOP = -1, 
       TEL = REPLACE(TEL, '*', ''),
       TEL1 = REPLACE(TEL1, '*', ''),
       TEL2 = REPLACE(TEL2, '*', ''),
       TEL3 = REPLACE(TEL3, '*', ''),
       TEL4 = REPLACE(TEL4, '*', '')
FROM [CALLFILE_BACKOFFICE].DBO.[C1_BKO_OCORRENCIA_ACOMPANHAMENTO_PREVIEW] AS A
    JOIN [CUSTOMER_BACKOFFICE].[DBO].[CUSTOMER_BACKOFFICE_OCORRENCIA] AS B ON A.INDICE = B.INDICE
WHERE A.PRIORITE <= 0
    and PRIORITE > -990
    and PRIORITE <> -777
    AND LIB_STATUS IN ('ABSENT','NAO TABULADO','Fax','Repondeur System','Wrong Number System','')
    AND (DATE < CONVERT(VARCHAR(10),GETDATE(),112)
    OR (DATE = CONVERT(VARCHAR(10),GETDATE(),112)
    AND HEURE <=  REPLACE(CONVERT(VARCHAR(5),DATEADD(MINUTE,-30,GETDATE()),108),':','')))